### ISSUE TITLE
Can you compile v0.3 in release mode?

### ISSUE THREAD

**Issue by custom90gt** [FlyGoat/RyzenAdj#10]
I am trying to use 0.3 but because it was compiled in debug mode I cannot run it without installing visual studio.  Is it possible to compile it in release mode so vcruntime140D.dll and ucrtbaseD.dll are not required.
Thanks!

**Comment by FlyGoat** [comment]
Should be fixed

**Comment by custom90gt** [comment]
Works perfectly, thanks!
