### ISSUE TITLE
Does it support 5800u?

### ISSUE THREAD

**Issue by kiwiw** [FlyGoat/RyzenAdj#119]
I use hp zhan 66 4th edition, Cpu is 5800u,  hope can support , thanks!

**Comment by Falcosc** [comment]
Hi @kiwiw 

we don't have any of these, but we did guessed some things.

Would be cool if you could get feedback for option support on your Cezanne.
Then we could add it to our support matrix: https://github.com/FlyGoat/RyzenAdj/wiki/Supported-Models#cpu-family-support-matrix

**Comment by kiwiw** [comment]
Sorry, i just canceled the order of my computer. so cant feedback.

**Comment by FlyGoat** [comment]
Tested on ROG Flow X13.

**Comment by Falcosc** [comment]
I did put the test results of the 5800HS into our support table. Because it has even the same issues as Renoir, it will be the same for all Cezanne CPUs
