### ISSUE TITLE
Version 0.8.1 gives error in Task manager

### ISSUE THREAD

**Issue by jumpingjackflash5** [FlyGoat/RyzenAdj#146]
Version 0.8.1 gives error 0xc0000005 as a result when being run in Task manager as scheduled task. Although it probably still works OK, I returned to 0.8.0 which returns success (0x0) and also sets the parameters correctly on my Ryzen 3200U.

**Comment by Falcosc** [comment]
Could you share some more details?

**Comment by jumpingjackflash5** [comment]
¨
![obrazek](https://user-images.githubusercontent.com/49901997/117312166-233cc280-ae85-11eb-8ec8-7b4e419ee9a9.png)

Here in the results of a task was seen the error code 0xc0000005 I wrote above.
With 0.8.0 there is written Task finished succesfully (my screen is in Czech language).

**Comment by jumpingjackflash5** [comment]
My task has got simple command line, I do not use the scripts that are included.

![obrazek](https://user-images.githubusercontent.com/49901997/117312475-5bdc9c00-ae85-11eb-867a-cc6f5586900c.png)

**Comment by Falcosc** [comment]
@jumpingjackflash5 please try to get the error message by sending the command output somewhere

`c:\ryzenadj\ryzenadj.exe --tctl-temp=70 >> c:\ryzenadj\output.log`

**Comment by jumpingjackflash5** [comment]
On command line it is OK. It givees that error just as a result in the task scheduler.

**Comment by Falcosc** [comment]
> On command line it is OK. It givees that error just as a result in the task scheduler.

please use `>> path\logfile` in your task scheduler and post the log when you get the error again.

**Comment by jumpingjackflash5** [comment]
I tried but that files is empty, even if I run it from batch file. When run from command line everything seems to be OK 
![obrazek](https://user-images.githubusercontent.com/49901997/117328708-2db28880-ae94-11eb-8a1c-1a32b809d36b.png)

**Comment by Falcosc** [comment]
`c:\ryzenadj\ryzenadj.exe --tctl-temp=70 >> c:\ryzenadj\output.log`

Will output only to output.log, try it in CMD and if it is working, you can use it in scheduler.

**Comment by jumpingjackflash5** [comment]
No. Version 0.8.1 does not output to log regardless of from where it is run. Only screen output from command line is OK.
Reverting to 0.8.0 which works completely OK.

**Comment by Falcosc** [comment]
Does 0.8.0 output to `c:\ryzenadj\output.log` ?

**Comment by jumpingjackflash5** [comment]
Yes, perfectly

**Comment by Falcosc** [comment]
Thank you, found the error.

**Comment by jumpingjackflash5** [comment]
Ok, happy to hear that!

**Comment by Falcosc** [comment]
@jumpingjackflash5 have a look at the 0.8.2 build:
https://github.com/FlyGoat/RyzenAdj/actions/runs/817695928

**Comment by jumpingjackflash5** [comment]
Runs succesfully now!
