### ISSUE TITLE
How to provide testing information?

### ISSUE THREAD

**Issue by Orangian** [FlyGoat/RyzenAdj#155]
Hi. I have an Asus Vivobook F512D with a Ryzen 3500u and I use every parameter (that ryzenadj -i shows) except for apu-slow-limit, apu-skin-temp and dgpu-skin-temp and I was wondering if I could provide some more testing information for y'all. This software has been amazing and quite useful in making my laptop last over 8 hours of constant use (even with a severly degraded battery) so I want to give back to the developers. Is there a way to help you out with the Picasso CPU's and give more testing information?

**Comment by FlyGoat** [comment]
Feel free to document your findings in wiki.
