### ISSUE TITLE
tempreture limit issue

### ISSUE THREAD

**Issue by YuriKruglov** [FlyGoat/RyzenAdj#158]
When blender rendering no tempreture limit at all. 4800H 1650ti 16RAM
![Сниваыаывыавываывамок](https://user-images.githubusercontent.com/50294035/122598646-89bd1f00-d086-11eb-8458-8c1841892259.PNG)

**Comment by Falcosc** [comment]
Please execute ryzenAdj --info to see if your temperature limit actually got applied.

It is normal that something doesn't work if you don't check that:
https://github.com/FlyGoat/RyzenAdj/wiki/FAQ#temperature-or-power-limit-does-not-work
