### ISSUE TITLE
Not an issue, just asking something.

### ISSUE THREAD

**Issue by cronyakatsuki** [FlyGoat/RyzenAdj#159]
Hi i recently create a scoop bucket for easier install of ryzenadj on windows.
So I wanted to ask if you could add it into readme for easier installation on windows.
If you wanted to I can also remove it.

**Comment by Falcosc** [comment]
We don't maintain package manager entries. But you can feel free to maintain scoop, thank you.

I don't add scoop to the main readme because adding a package manager section would mean to add all existing linux distro package manager entries as well.

**Comment by cronyakatsuki** [comment]
Ok, thank you very much for your answer.
