### ISSUE TITLE
TDP settings keep restoring to default even though the app is running in background

### ISSUE THREAD

**Issue by n3onis** [FlyGoat/RyzenAdj#16]
Is this a known issue? I've had no success changing TDP limits. They do change at first, but then they reset every time.

**Comment by n3onis** [comment]
Found a [comment on reddit](https://www.reddit.com/r/Amd/comments/anbl95/ryzen_master_for_mobile_ryzen_modify/efv3wwr?utm_source=share&utm_medium=web2x) stating the same. I wonder what you need to fix this?

**Comment by n3onis** [comment]
Just found your [comment on reddit](https://www.reddit.com/r/Amd/comments/anbl95/ryzen_master_for_mobile_ryzen_modify/efv3wwr?utm_source=share&utm_medium=web2x). I can extract my DSDT and send it to you, if it helps.

**Comment by FlyGoat** [comment]
In fact I am still not sure about the reason. But you can try to set stapm time into a very big value. Some users reported it may help.

**Comment by FlyGoat** [comment]
Remove ALIB calls in dsdt works on some machines but not all.

**Comment by speedracerlo** [comment]
I have the same problem here.  I've used v0.3 and it works at first, but sometime later it reverts back to original.  How do I remove ALIB calls?

**Comment by speedracerlo** [comment]
I have the same problem here.  I've used v0.3 and it works at first, but sometime later it reverts back to original.  How do I remove ALIB calls?

**Comment by n3onis** [comment]
> 
> 
> I have the same problem here. I've used v0.3 and it works at first, but sometime later it reverts back to original. How do I remove ALIB calls?

The best solution I've found for now is using the Ryzen Controller GUI alternative linked on this repo and setting the re-apply timer to a few seconds.
