### ISSUE TITLE
Van Gough/Steam Deck support?

### ISSUE THREAD

**Issue by brucethemoose** [FlyGoat/RyzenAdj#161]
Is support for the Steam Deck's APU in the cards?

I realize this is probably unanswerable until we get the actual hardware.

**Comment by FlyGoat** [comment]
We can't say it without testing on actual machine. We don't have clues about the SMU interface of these platforms.

**Comment by JamesCJ60** [comment]
Hi,
Steam Deck support has recently been added to RyzenADJ, and we have received confirmation of it working on the Steam Deck.
