### ISSUE TITLE
Unable to execuate the software

### ISSUE THREAD

**Issue by bigHeadAzuo** [FlyGoat/RyzenAdj#162]
Original title: 这个软件打不开

ryzenadj 应用程序是灰色的，怎么用？

Translated by FlyGoat.

**Comment by FlyGoat** [comment]
请参考GUI软件 https://ryzencontroller.com/，RyzenAdj不是为一般用户设计的，是这些GUI软件的后端。

**Comment by do-n-khanh** [comment]
does https://gitlab.com/ryzen-controller-team/ryzen-controller/-/releases/2.3.0 use your v0.8.2 ?

**Comment by FlyGoat** [comment]
> does https://gitlab.com/ryzen-controller-team/ryzen-controller/-/releases/2.3.0 use your v0.8.2 ?

yes

**Comment by do-n-khanh** [comment]
Thanks. I am using zhen 66 pro 5800u. I tried ryzen-controller setting like below. However, when I do the test, it runs at 28w for a few seconds, and then drops to 25w for 1-2 mins, and then drops to 15 w. Do you know what is wrong with my settings? 

![image](https://user-images.githubusercontent.com/3012507/129064240-e50bc003-6544-453f-96eb-8a53b35a4210.png)
![image](https://user-images.githubusercontent.com/3012507/129064380-6ee9e200-7b6a-4e2b-8995-3d1ccb579d2e.png)

**Comment by Falcosc** [comment]
> 
> 
> Thanks. I am using zhen 66 pro 5800u. I tried ryzen-controller setting like below. However, when I do the test, it runs at 28w for a few seconds, and then drops to 25w for 1-2 mins, and then drops to 15 w. Do you know what is wrong with my settings?

CPU TDP (W) used the stapm-limit parameter, then this will not change your 15W limit. Read this:
https://github.com/FlyGoat/RyzenAdj/wiki/Supported-Models#sttv2-dependencies-renoir--lucienne--cezanne

And read this: https://github.com/FlyGoat/RyzenAdj/wiki/Options#stapm

And to really understand what is happening you need to read this whole page, it applies to your generation as well.
https://github.com/FlyGoat/RyzenAdj/wiki/Renoir-Tuning-Guide

And don't forget our FAQ:
https://github.com/FlyGoat/RyzenAdj/wiki/FAQ
