### ISSUE TITLE
not working on Acer Nitro 5

### ISSUE THREAD

**Issue by Benman2785** [FlyGoat/RyzenAdj#17]
hi, it doesnt work on my Acer Nitro 5 with Ryzen 5 2500U
no difference between 12W or 35W

**Comment by FlyGoat** [comment]
Hi, a lot of dudes have verified it works perfectly on your model.
Could you please use AMD uprof to check if the change valid?

**Comment by Benman2785** [comment]
![image](https://user-images.githubusercontent.com/21282980/55906523-bcc91580-5bd4-11e9-8b96-47e80a0812f7.png)
it changes the limits but CPU still limits itself and i dont know why!

**Comment by Benman2785** [comment]
![image](https://user-images.githubusercontent.com/21282980/55908377-93f74f00-5bd9-11e9-8add-8dd24810ad3c.png)
highest performance i have running the APU on stock - without changing any value

**Comment by FlyGoat** [comment]
Did you perform any BIOS update? 
So it should be something wrong with SMU.

**Comment by Benman2785** [comment]
i use 1.13
what is the SMU i need to use?

**Comment by Benman2785** [comment]
i use SMU v30.80
