### ISSUE TITLE
Customize stapm-limit and other values when AC/battery mode

### ISSUE THREAD

**Issue by jinwk00** [FlyGoat/RyzenAdj#174]
As written in title, I want the stapm-limit to become 60000 instead of default 45000, is it possible to change? If not, are there any alternative that I can set up a script for?

**Comment by Falcosc** [comment]
https://github.com/FlyGoat/RyzenAdj/wiki/Options#stapm

- Gets overwritten by SSTv2.
- Only usable if you did disable SSTv2 (Zen2/Zen3)
- Only usable if you don't have SSTv2 (Zen or Zen+)

**Comment by jinwk00** [comment]
I mean, when I put my laptop into charger, then stapm/fast/slow automatically becomes 45000, 55000, 48000, is it possible to override this value to something else? And others too, e.g. VRM?

**Comment by Falcosc** [comment]
https://github.com/FlyGoat/RyzenAdj#windows-installation

**Comment by jinwk00** [comment]
@Falcosc I'm not talking about installation; I am wondering if default values when my AC gets connected or disconnected can be changed or not, even if it means to use a script. Please stay on topic what I am trying to explain.

**Comment by Falcosc** [comment]
No ryzenAdj does only apply values over SMU and can not be used to alter your factory power settings, you can only detect the state change and apply the values to overwrite the factory setting every time.

Not sure how Linux does apply the factory values, you may can hook into that: https://github.com/sibradzic/stapmlifier

**Comment by jinwk00** [comment]
Thank you, that's the answer I wanted to hear.
