### ISSUE TITLE
Aya Neo Pro 4800U doesn't work with RyzenAdj

### ISSUE THREAD

**Issue by ruineka** [FlyGoat/RyzenAdj#186]
I am unable to make any changes to the TDP or graphics frequency using either the commandline or Ryzen Controller on the Aya Neo Pro with the 4800U APU.

![photo_2022-02-01_19-20-51](https://user-images.githubusercontent.com/16360335/152078525-f3f46d74-d117-424b-88b8-2828508898a3.jpg)

**Comment by FlyGoat** [comment]
Please at least give us output of RyzenAdj. We have no clues about what;s going on behind Ryzen Controller.

**Comment by ruineka** [comment]
> Please at least give us output of RyzenAdj. We have no clues about what;s going on behind Ryzen Controller.

Absolutely, as soon I'm at the device I'll get this information for you.
