### ISSUE TITLE
Guys, there an way to this work with A10 7300 in fm2+ mobile plataform?

### ISSUE THREAD

**Issue by leonardcoutinho** [FlyGoat/RyzenAdj#19]
Guys, there an way to this work with A10 7300 in fm2+ mobile plataform? I have an A8 7150B and when I try Ryzenadj it can show Stapm tdp limits and etc, but when I try to apply it does nothing.

**Comment by FlyGoat** [comment]
Sorry, But the interface is totally different and I have no information about that.
