### ISSUE TITLE
set_oc_clk is rejected by SMU on mobile renoir apus

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [FlyGoat/RyzenAdj#198]
I am using a ryzen 7 4700u, any help? (on linux)
enable OC does not work either
disable OC works tho lol
just tried on a different laptop (from a different manufacturer)
it has a 4800h and it also does not work
this machine is running windows btw
is it a Cezanne and higher feature? or is it just a slightly different address??

**Comment by JamesCJ60** [comment]
Hi, the commands you are trying to use are for overclocking which no mobile APU supports.
