### ISSUE TITLE
Not working on ryzen 5 2500u on ubuntu

### ISSUE THREAD

**Issue by Yrahate7** [FlyGoat/RyzenAdj#20]
I ran the program as root user,but it shows the following,i installed the pcidev controller too.
![Screenshot from 2019-05-05 20-19-04](https://user-images.githubusercontent.com/11058072/57195697-3b666800-6f73-11e9-9e45-ee41d287e3f4.png)

**Comment by FlyGoat** [comment]
Some users reported Ubuntu declined PCI config space RW too, I have no idea about that.
It works fine on Debian and ArchLinux.
I'm not sure if we can unlock it on Ubuntu.

**Comment by GoelBiju** [comment]
@FlyGoat I have tested it on Ubuntu 18.04 LTS. It works fine as long as you use it as a sudo user.

**Comment by chaos-dremel** [comment]
@FlyGoat @Yrahate7 I had same issue. But when I disabled secure boot (in BIOS) the problem "magically" disappeared.

**Comment by Yrahate7** [comment]
@FlyGoat @chaos-dremel , Can confirm. Disabling Secure boot in BIOS fixes the issue
