### ISSUE TITLE
[bug?] _do_adjust_psmu(OPT) never gets called

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [FlyGoat/RyzenAdj#200]
```
EXP int CALL set_oc_volt(ryzen_access ry, uint32_t value) {
	switch (ry->family)
	{
	case FAM_LUCIENNE:
	case FAM_RENOIR:
	case FAM_CEZANNE:
	case FAM_REMBRANDT:
		_do_adjust(0x33);
		_do_adjust_psmu(0x1b);
		break;
	}
	return ADJ_ERR_FAM_UNSUPPORTED;
}`
```
This might be a mistake in me reading the code, but I doubt it.
Basically, _do_adjust is a macro that returns a value once its done executing, so how is do_adjust_psmu ever going to get called in this scenario? (_do_adjust returns, so there is no way for this second macro to be called)

**Comment by FlyGoat** [comment]
Yep can confirm it's a problem.

@JamesCJ60 what was your intention?

**Comment by JamesCJ60** [comment]
An issue was encountered when testing on desktop APUs when using the CLI and dll versions of RyzenAdj. 

One would only accept PSMU and other one only accept the normal MP1 _do_adjust for the overclocking and voltage control commands. 

This was done so they both worked regardless of which RyzenAdj implementation is used. Without it, only one was be able to apply the changes for these options.

**Comment by Etaash-mathamsetty** [comment]
> An issue was encountered when testing on desktop APUs when using the CLI and dll versions of RyzenAdj.
> 
> One would only accept PSMU and other one only accept the normal MP1 _do_adjust for the overclocking and voltage control commands.
> 
> This was done so they both worked regardless of which RyzenAdj implementation is used. Without it, only one was be able to apply the changes for these options.

how does that work then? becuase if only _do_adjust is going to be called, _do_adjust_psmu will never get called no matter what (based on what I read)

**Comment by Etaash-mathamsetty** [comment]
I think fixing this could also fix 
#198 
but that might be something else entirely

**Comment by FlyGoat** [comment]
Finally caught some time to look into this.
@Etaash-mathamsetty @JamesCJ60 could you please review and test commit on [err_handling](https://github.com/FlyGoat/RyzenAdj/tree/err_handling) branch?

If you would like to have a Windows executable here is CI output: https://github.com/FlyGoat/RyzenAdj/actions/runs/2812559586

Thanks.

**Comment by Etaash-mathamsetty** [comment]
> Finally caught some time to look into this. @Etaash-mathamsetty @JamesCJ60 could you please review and test commit on [err_handling](https://github.com/FlyGoat/RyzenAdj/tree/err_handling) branch?
> 
> If you would like to have a Windows executable here is CI output: https://github.com/FlyGoat/RyzenAdj/actions/runs/2812559586
> 
> Thanks.
none of the OC functions work and GFX CLK broke after a bios update, but looking over the source code, everything seems fine

**Comment by JamesCJ60** [comment]
> > Finally caught some time to look into this. @Etaash-mathamsetty @JamesCJ60 could you please review and test commit on [err_handling](https://github.com/FlyGoat/RyzenAdj/tree/err_handling) branch?
> > If you would like to have a Windows executable here is CI output: https://github.com/FlyGoat/RyzenAdj/actions/runs/2812559586
> > Thanks.
> 
> none of the OC functions work and GFX CLK broke after a bios update, but looking over the source code, everything seems fine when running it, the PSMU and SMU stuff are both being tried

OC functions only work on 4000+G APUs

**Comment by Etaash-mathamsetty** [comment]
> > > Finally caught some time to look into this. @Etaash-mathamsetty @JamesCJ60 could you please review and test commit on [err_handling](https://github.com/FlyGoat/RyzenAdj/tree/err_handling) branch?
> > > If you would like to have a Windows executable here is CI output: https://github.com/FlyGoat/RyzenAdj/actions/runs/2812559586
> > > Thanks.
> > 
> > none of the OC functions work and GFX CLK broke after a bios update, but looking over the source code, everything seems fine when running it, the PSMU and SMU stuff are both being tried
> 
> OC functions only work on 4000+G APUs 

Oh really, i thought they work on all 4000 series apus including mobile ones, might want to add a note about it
