### ISSUE TITLE
[FAIL] W11 Home, Asus AiO M5401

### ISSUE THREAD

**Issue by juanpc2018** [FlyGoat/RyzenAdj#201]
Using GUI 
https://gitlab.com/ryzen-controller-team/ryzen-controller

Ryzen 7 5700U
Latest Bios / UEFI 305
Very limited Bios, does Not have a way to Turn-OFF HyperThreading / SMP.
it must have a hidden secret menu somewhere but i dont know how to access.
i was "Administrator" account. F2.
Very limited Toy Bios.

W11 Home does Not have W10 compatibility mode.
Blank Screen / White Window.

There is other models, in the: M5401WU
Ryzen R7 5825U W11 Pro
Ryzen 7 5700U W10 Home
Ryzen 5 5500U W10 

https://www.asus.com/us/Displays-Desktops/All-in-One-PCs/Zen-AiO/Zen-AiO-24-M5401/
https://www.asus.com/Displays-Desktops/All-in-One-PCs/Zen-AiO/Zen-AiO-24-M5401/

P.D. The Only way to force less cores was:
msconfig Boot options in cmd
i think i tested Run in Administrator mode.
Not my machine, friend / client.

**Comment by FlyGoat** [comment]
We have no way to touch SMT settings in operating system. Only possible with BIOS Mod.
