### ISSUE TITLE
RyzenAdj stopped working after update

### ISSUE THREAD

**Issue by Vadosssss** [FlyGoat/RyzenAdj#208]
I use the package from AUR, and after the latest update - I got this:
`~ » sudo ryzenadj --info
CPU Family: Cezanne
SMU BIOS Interface Version: 18
Version: v0.11.0 
set_coall is rejected by SMU
set_coper is rejected by SMU
set_cogfx is not supported on this SMU`
I can confirm that it was working in previous versions. Any suggests?
CPU: Ryzen 7 5800H
OS: Arch Linux

**Comment by FlyGoat** [comment]
It has been fixed in v0.11.1. Please update to that version.

**Comment by lavrovvv** [comment]
Sorry for the late reply, now it works. Thanks!

**Comment by Vadosssss** [comment]
Sorry for the late reply, now it works. Thanks!
