### ISSUE TITLE
STAPM Time does not apply on Linux

### ISSUE THREAD

**Issue by bagusnl** [FlyGoat/RyzenAdj#209]
I can't seem to change STAPM Time const. on my setup using RyzenAdj on Linux ~~but it works fine on Windows~~.

Setup:
AMD Ryzen 3 3200U on Acer Aspire 3 A315-41-R69L
Ubuntu 22.04, tried both 5.18.16-xanmod1 and Ubuntu provided 5.15.0-46-generic
HWProbe link: https://linux-hardware.org/?probe=6a9c811ea3

```
bagusnl@linux-acer:~/Downloads/RyzenAdj/build$ sudo ./ryzenadj --stapm-time=1000
SMU_SERVICE REQ_ID:0x1e
SMU_SERVICE REQ: arg0: 0x3e8, arg1:0x0, arg2:0x0, arg3:0x0, arg4: 0x0, arg5: 0x0
SMU_SERVICE REP: REP: 0x1, arg0: 0x3e8, arg1:0x0, arg2:0x0, arg3:0x0, arg4: 0x0, arg5: 0x0
Sucessfully set stapm_time to 1000
bagusnl@linux-acer:~/Downloads/RyzenAdj/build$ sudo ./ryzenadj -i
CPU Family: Picasso
SMU_SERVICE REQ_ID:0x3
SMU_SERVICE REQ: arg0: 0x0, arg1:0x0, arg2:0x0, arg3:0x0, arg4: 0x0, arg5: 0x0
SMU_SERVICE REP: REP: 0x1, arg0: 0x8, arg1:0x0, arg2:0x0, arg3:0x0, arg4: 0x0, arg5: 0x0
SMU BIOS Interface Version: 8
Version: v0.11.1 
init_table
SMU_SERVICE REQ_ID:0xc
SMU_SERVICE REQ: arg0: 0x0, arg1:0x0, arg2:0x0, arg3:0x0, arg4: 0x0, arg5: 0x0
SMU_SERVICE REP: REP: 0x1, arg0: 0x1e0004, arg1:0x0, arg2:0x0, arg3:0x0, arg4: 0x0, arg5: 0x0
SMU_SERVICE REQ_ID:0xb
SMU_SERVICE REQ: arg0: 0x3, arg1:0x0, arg2:0x0, arg3:0x0, arg4: 0x0, arg5: 0x0
SMU_SERVICE REP: REP: 0x1, arg0: 0xaf766000, arg1:0x0, arg2:0x0, arg3:0x0, arg4: 0x0, arg5: 0x0
SMU_SERVICE REQ_ID:0x3d
SMU_SERVICE REQ: arg0: 0x3, arg1:0x0, arg2:0x0, arg3:0x0, arg4: 0x0, arg5: 0x0
SMU_SERVICE REP: REP: 0x1, arg0: 0x3, arg1:0x0, arg2:0x0, arg3:0x0, arg4: 0x0, arg5: 0x0
PM Table Version: 1e0004
SMU_SERVICE REQ_ID:0x3d
SMU_SERVICE REQ: arg0: 0x3, arg1:0x0, arg2:0x0, arg3:0x0, arg4: 0x0, arg5: 0x0
SMU_SERVICE REP: REP: 0x1, arg0: 0x3, arg1:0x0, arg2:0x0, arg3:0x0, arg4: 0x0, arg5: 0x0
```
|        Name         |   Value   |      Paramter      |
|---------------------|-----------|--------------------|
| STAPM LIMIT         |    30.000 | stapm-limit        |
| STAPM VALUE         |     9.555 |                    |
| PPT LIMIT FAST      |    30.000 | fast-limit         |
| PPT VALUE FAST      |     9.560 |                    |
| PPT LIMIT SLOW      |    25.000 | slow-limit         |
| PPT VALUE SLOW      |    11.780 |                    |
| StapmTimeConst      |     1.000 | stapm-time         |
| SlowPPTTimeConst    |   100.000 | slow-time          |
| PPT LIMIT APU       |       nan | apu-slow-limit     |
| PPT VALUE APU       |       nan |                    |
| TDC LIMIT VDD       |    45.000 | vrm-current        |
| TDC VALUE VDD       |     3.058 |                    |
| TDC LIMIT SOC       |    18.000 | vrmsoc-current     |
| TDC VALUE SOC       |     3.474 |                    |
| EDC LIMIT VDD       |    60.000 | vrmmax-current     |
| EDC VALUE VDD       |    48.897 |                    |
| EDC LIMIT SOC       |    25.000 | vrmsocmax-current  |
| EDC VALUE SOC       |     5.736 |                    |
| THM LIMIT CORE      |    89.000 | tctl-temp          |
| THM VALUE CORE      |    44.540 |                    |
| STT LIMIT APU       |       nan | apu-skin-temp      |
| STT VALUE APU       |       nan |                    |
| STT LIMIT dGPU      |       nan | dgpu-skin-temp     |
| STT VALUE dGPU      |       nan |                    |
| CCLK Boost SETPOINT |    70.000 | power-saving /     |
| CCLK BUSY VALUE     |    33.939 | max-performance    |

Power table dump:
[tabledump.log](https://github.com/FlyGoat/RyzenAdj/files/9308762/tabledump.log)

Edit: I forgot to say I'm currently using the latest commit of the repo, but I tried on 0.10.0 release and it still not working

Update: just did a double check and it seems that it also not working under Windows, I'll check some BIOS settings that might interfere with it

**Comment by Falcosc** [comment]
The table output does show that you did successful change the value to
StapmTimeConst | 1.000 | stapm-time
-- | -- | --

If this value does not change the behavior of your CPU power management, then it may not be used by your CPU generation.
