### ISSUE TITLE
Can you compile Picasso Supported version in release mode?

### ISSUE THREAD

**Issue by neurosis89** [FlyGoat/RyzenAdj#21]
Got  [these errors](https://gitlab.com/le.storm1er/ryzen-controller/uploads/e00e983430ab9ed077c8ac40f1f3de6b/20190511161718.png) while building solution in Visual Studio Community 2019. Since I'm a noob I don‘t know how to solve them，should I install libpci for Windows？Thank you very much！

**Comment by FlyGoat** [comment]
Sorry but I don't have Windows build environment as for now.

**Comment by FlyGoat** [comment]
Built.
