### ISSUE TITLE
Setting vrmmax-current broken on Ryzen 5600H (Cezanne)

### ISSUE THREAD

**Issue by BrannigansLaw** [FlyGoat/RyzenAdj#211]
Using "ryzenadj --vrmmax-current=60" and then doing "ryzenadj --info" shows vrmmax-current at 0.06. Power consumption barely goes above 6 Watts so it's definitely affecting the current. Note that I'm using a Gentoo Linux kernel (5.19.4) built using a custom kernel config with the new AMD P-State driver. So it could be my setup.

**Comment by fishchev** [comment]
RyzenAdj expects values in mA, mW and seconds. So for 60A you need 60000
`-k, --vrmmax-current=<u32> VRM Maximum Current Limit - EDC LIMIT VDD (mA)`
