### ISSUE TITLE
Setup an RPM COPR repo?

### ISSUE THREAD

**Issue by christophehenry** [FlyGoat/RyzenAdj#213]
I just wrote a `.spec` to compile RyzenAdj. I would like to know if you are willing to setup [an RPM repo using COPR](https://copr.fedorainfracloud.org/) so that RPM users can have auto-update for every release you make. You can use [the Github webhooks](https://docs.pagure.org/copr.copr/user_documentation.html#github-webhooks) to rebuild the RPM with every new release.

Would you be interested?

**Comment by FlyGoat** [comment]
I’m happy if anyone volunteer to help me write spec file :-)

**Comment by christophehenry** [comment]
Done.
