### ISSUE TITLE
Support 3900X?

### ISSUE THREAD

**Issue by christophehenry** [FlyGoat/RyzenAdj#217]
From what I read AMD Ryzen 9 3900X is a Zen 2 architechture so it should fall under [the lucienne family, if I understand correctly](https://github.com/FlyGoat/RyzenAdj/blob/317acb7b057e8027a745c5777aa6136597b59c75/lib/cpuid.c#L60-L61)? Sadly, its model number (113), is not currently supported.

I am not sure I have enough knowledge on the matter. Is it safe to add it in the code under the lucienne family?

**Comment by JamesCJ60** [comment]
Hi, RyzenAdj only supports Ryzen APUs, Ryzen 9 3900X is a Ryzen CPU and falls under the Matisse family.
