### ISSUE TITLE
CPU Frequency tweak

### ISSUE THREAD

**Issue by Godl1nk** [FlyGoat/RyzenAdj#223]
Tweak CPU frequency based on number of cores active. Something like throttlestop's cpu boost ratio limit.
This can be done in many ways, as well as via power plan (power plan only sets a limit regardless of cores active), basically even locked cpus can make use of this if its done by modifying power plan settings

**Comment by FlyGoat** [comment]
Well as RyzenAdj aims to be a lightweight tool to adjust hardware parameters directly, doing so is beyond our design.
You may check other tools like AATU: https://github.com/JamesCJ60/Universal-x86-Tuning-Utility
