### ISSUE TITLE
Feature request: SMT toggle option

### ISSUE THREAD

**Issue by liphistius** [FlyGoat/RyzenAdj#23]
Using SMT is in some cases slower, produces more heat and hence reduces battery life on the go.
Is it possible to add the option for turning it off or is this something that can only be done through the BIOS?

If you have the time and willingness it would be great if you could add this.
If you have any suggestions on where to get started I'd be interested in trying it out.

Thanks :)

**Comment by FlyGoat** [comment]
According to my knowledge, it's nearly impossible to disable SMT in runtime.
And the SMU interface didn't give us this option.
