### ISSUE TITLE
doesn't work anymore on Ryzen 5 2500u new bios update hp F.31

### ISSUE THREAD

**Issue by shakumaru** [FlyGoat/RyzenAdj#24]
Not a Ryzen NB SMU, BIOS Interface Ver: 0x7
Unable to init ryzenadj, check permission

**Comment by razorbackdb** [comment]
Can confirm, same happened to me too, both in windows and linux. Triend to downgrade the bios but no use, hp seems to have blocked the downgrade at least on my case. Laptop is HP Pavilion - 15-cw0005la.

**Comment by FlyGoat** [comment]
Seems like AMD added a lot of new Interface Version.
I'm going to disable the check.

**Comment by shakumaru** [comment]
thank you

**Comment by FlyGoat** [comment]
Latest code had fixed the issue.
I'm going to make a release later.

**Comment by shakumaru** [comment]
should it works with the last version (1.12.3)? the issue still there

**Comment by razorbackdb** [comment]
@FlyGoat worked for me on windows, thank you!, haven't tried linux yet, @shakumaru try this build
[x64-Release.zip](https://github.com/FlyGoat/RyzenAdj/files/3250006/x64-Release.zip)

**Comment by FlyGoat** [comment]
The latest release fixed the issue,

**Comment by shakumaru** [comment]
thanks @razorbackdb the problem was ryzenadj.exe i dont know why
