### ISSUE TITLE
problem with microsoft visual c++

### ISSUE THREAD

**Issue by marcelhdhd** [FlyGoat/RyzenAdj#27]
When I try to start the prebuild .exe I get the vcruntime140D.dll is missing and then the ucrtbased.dll is missing error. I tried to reinstall microsoft visual studio redistibutable 2015 - 2019 but no luck so far. Have I missed something? I can't seem to get it to work. Thank you and have a nice day!

**Comment by FlyGoat** [comment]
Solved.
My fault Just updated to VS2019 and something went wrong with build profile.
Please download the release tarball again, this version it should work.
