### ISSUE TITLE
[Question] Is there a similar utility for mobile Intel CPUs?

### ISSUE THREAD

**Issue by birdie-github** [FlyGoat/RyzenAdj#288]
Sorry for being offtopic.

Is there a similar utility for mobile Intel CPUs? ICL/TGL/ADL/RPL/MTL?

I've not been able to find anything.

**Comment by Falcosc** [comment]
Intel Extreme Tuning Utility

Intel XTU

**Comment by birdie-github** [comment]
Thanks, it's Windows only, I was looking for something working in Linux.

**Comment by FlyGoat** [comment]
https://github.com/horshack-dpreview/setPL
https://github.com/georgewhewell/undervolt

**Comment by birdie-github** [comment]
I've just discovered an extra tool for AMD CPUs:

https://github.com/DavidS95/Smokeless_UMAF

@FlyGoat could be interesting for you too.
