### ISSUE TITLE
[Docs] List of experience values for devices?

### ISSUE THREAD

**Issue by Trollwut** [FlyGoat/RyzenAdj#30]
Hey folks!

Very nice software and I like playing around with it. I've got an E585, which has been a throttled TDP from factory, god knows why.

How about a list of devices and values people here have tested that work in normal conditions?

Like that we have a table for models and users can add their values, so when others want to tinker around they have some values where they can orient themselves at.

**Comment by FlyGoat** [comment]
Sorry but read out values is still unimplemented due to technical reason.
Reverse Engineering of uProf shown some ways however still a little bit hard to implement.

**Comment by FlyGoat** [comment]
Users are welcomed to apply their experience values to the wiki.

**Comment by Trollwut** [comment]
Would maybe creating a template table help users to see that there is something to contribute to?
