### ISSUE TITLE
Are ryzen desktop processors supported?

### ISSUE THREAD

**Issue by N46AN** [FlyGoat/RyzenAdj#32]
In #12 one of the contributors states that 
> All of the Ryzen Mobile range and the Ryzen desktop should be supported. I believe the desktop processors are unlocked so you might...

I tried running this tool with Ryzen 5 2600x on a B450 MB but got this message after a long delay:

> $ ryzenadj.exe --tctl-temp=60
> Not a Ryzen NB SMU, BIOS Interface Ver: 0x0
> $

OS is Windows 10.

Thanks!

**Comment by FlyGoat** [comment]
BIOS Interface 0x0 means CPU have totally no respond to service requests.
I've tested RyzenADJ on R5 2200G with AGESA RavenPi 1.1.0.
But I'm not sure if recent SMU/BIOS update (ComboPi) had changed that interface.

**Comment by bobafetthotmail** [comment]
I've ran this on a Ryzen 3 PRO 2200GE (that I bought from Aliexpress, I'm trying to increase its power limits) on a AB350M Pro4 with BIOS version 5.90 https://www.asrock.com/mb/AMD/AB350M%20Pro4/index.asp#BIOS on Linux.

It does not seem to error out, but I have no other way to tell if this actually does anything.

```
sudo ./ryzenadj --stapm-limit=65000 --fast-limit=65000 --slow-limit=65000 --tctl-temp=90
[sudo] password for root: 
Sucessfully set stapm_limit to fde8
Sucessfully set fast_limit to fde8
Sucessfully set slow_limit to fde8
Sucessfully set tctl_temp to 5a
```

**Comment by OneB1t** [comment]
temperature is working for me on 200GE but rest like GFX clock im only able break it but cant set it to normal value

**Comment by OneB1t** [comment]
Ok now i know how to find if CRavenCPU::IsOverClockable this is MSR register 0xC0010292 first bit 0x10000000 represents if CPU can be overclocked (inside code they are checking that via & 0x1F8000 command)
1 means overclock disabled
0 means overclock enabled

![image](https://user-images.githubusercontent.com/320479/72211276-ecd97800-34c8-11ea-8e32-9826a450f515.png)
