### ISSUE TITLE
Rejecting by SMU

### ISSUE THREAD

**Issue by Toxpox** [FlyGoat/RyzenAdj#326]
Laptop model: Acer Nitro 16 (AN16-41)
CPU: 7840HS // Phoenix

I cannot change some values.

STAPM seems succesfully changed but its not. I know there is a STTv2.

All core Curve Optimizer and Per core Curve Optimizer is only works in "-1" value, other than that "rejected by SMU".

In NitroSense (Acer's program) Turbo mode STAPM is 60 and Performance mode STAPM is 45.

I can change same values:
Fast and slow limits (fast max=100W // slow max=95W) 
EDC and TDC limits ( EDC max= 140A // TDC max=80A)

Simply I cannot get higher values than Turbo profile. 

//Edit: Seems like "--skin-temp-limit" is working for STAPM. 
But I need to change Curve Optimizer.

**Comment by JamesCJ60** [comment]
Hi, the 7840HS does not support Curve Optimiser. This feature is only unlocked by AMD on the 7940HS/8945HS.
