### ISSUE TITLE
It Does not work on Acer 5 A315-41G - Ryzen 5 2500U

### ISSUE THREAD

**Issue by TheBishop1996** [FlyGoat/RyzenAdj#34]
I can change the thresholds using the program, and I can see the change using AMD uProf. But the actual power supplied to the processor does not go beyond the factory limited 15w while stress testing, even with cooling to spare.

**Comment by Benman2785** [comment]
same problem with Acer Nitro 5 with Ryzen 2500u

it changes everything i uProf but it doesnt affect performance

**Comment by ThinkAndFly** [comment]
Bishop: You need a tool called RyzenTest to unlock the factorylimit.

Benman, I think in your case the problem is that the changes don't last. I'm trying to find a way to make then last, cause in my case is the same.
