### ISSUE TITLE
Renoir support. Offering help

### ISSUE THREAD

**Issue by koriwi** [FlyGoat/RyzenAdj#46]
Haven't read anything about Renoir here.
My laptop should arrive this or next week. If I can help (mainly using Linux) let me know.

**Comment by FlyGoat** [comment]
Sorry but I'm not going to reverse engineering Renior's SMU stuff because lack of time and information.

I'm happy to add Renior support if somebody can give me a list of Renior's SMU call.

**Comment by koriwi** [comment]
No problem. 
I don't know if you know [this](https://github.com/irusanov/ZenStates) or how much it helps (because i don't know how much desktop will differ from mobile)

**Comment by koriwi** [comment]
OK. I found this Video  where he talks about lenovos vantage software which allows to enable the performance mode. Which allows for 42 watts peaks and 37watts sustained tdp.
Timestamps 2:10 and 3:38
 https://youtu.be/3jf7itO2YKg

Is there a way to "easily" catch the smu calls?

**Comment by koriwi** [comment]
For everyone finding this. Reverse engineering seems to be somewhat complete: https://github.com/FlyGoat/ryzen_nb_smu/issues/3

**Comment by FlyGoat** [comment]
I'm going to do sth with the effort when I have time:-)

**Comment by irusanov** [comment]
It seems to share the same SMU addresses as other APUs. Available commands are rather limited though. It would be interesting if the trick with P-States still works.

**Comment by koriwi** [comment]
Ok, after waiting almost 7 weeks, my laptop arrived. Is there something i should test?

**Comment by FlyGoat** [comment]
> 
> 
> Ok, after waiting almost 7 weeks, my laptop arrived. Is there something i should test?

Now Renoir is supported. I'm goting to close this issue.
