### ISSUE TITLE
Permission Issue on Windows

### ISSUE THREAD

**Issue by tarragon777** [FlyGoat/RyzenAdj#48]
WinRing0 Err: 0x2Unable to get PCI Obj
Unable to init ryzenadj, check permission
Help pls.
What can it be? Same error on the all versions of gui
:(
I am using HP G7 255, ryzen 2500U

**Comment by FlyGoat** [comment]
Which OS?

**Comment by tarragon777** [comment]
> Which OS?

Windows 10

**Comment by FlyGoat** [comment]
You'd better try to disable security features of Windows10.

**Comment by tarragon777** [comment]
> You'd better try to disable security features of Windows10.

i don`t know what happened but after booting OS today Gui version ryzenAdj 1.14.1 works fine now. Same issue stays on newer versions 2.00, 2.1.0, 2.2.0. Tried  to give rules for all users and run as admin, switched off windows defender etc. All these things really changed nothing. Will be using older version of GUI

**Comment by crimsoncandy** [comment]
Check if you have enabled Windows Defender> Device Security > Core Isolation > Memory Integrity. ryzenadj doesn't work with this enabled with same issue
