### ISSUE TITLE
Unable to apply ryzenadj

### ISSUE THREAD

**Issue by justBLACKperson** [FlyGoat/RyzenAdj#49]
At first, sorry for my not well English.
From day to day, ryzenadj tool stop works. 
I use for a daily basis Ryzen Controller. I tried a different tool,  Ryzen Mobile Adjustment Tool (Ryzen ADJ). It's shows that the changes are apply, but uProf don't show the changes. 
I'm working on windows 10.

**Comment by FlyGoat** [comment]
Any details?
