### ISSUE TITLE
How to restore the original value after modification

### ISSUE THREAD

**Issue by zhangyiming748** [FlyGoat/RyzenAdj#50]
I ran the demo on Windows, I just wanted to try it out, how to restore it to the original value now? I feel the computer's performance is significantly reduced

**Comment by FlyGoat** [comment]
Performance a reboot would reset all settings.

**Comment by zhangyiming748** [comment]
Do you mean that restarting the computer will restore all settings? Sorry my english is not very good, thanks for reply

**Comment by FlyGoat** [comment]
> Do you mean that restarting the computer will restore all settings? Sorry my english is not very good, thanks for reply

Exactly. All settings are volatile.

**Comment by stopyan** [comment]
是的，相关操作在电脑重启后初始化为主板bios默认值。

**Comment by mirh** [comment]
Couldn't there be a `--reset` parameter?
Ryzencontroller has a button for that for example.

**Comment by Falcosc** [comment]
It's the same problem like: https://github.com/FlyGoat/RyzenAdj/issues/57

Not possible to read out default values, so this would only possible if you store things which was done before.

This feature does only make sense for UI Integrations like Ryzen Controller or https://github.com/sbski/Renoir-Mobile-Tuning
