### ISSUE TITLE
Does it work without administrator privileges on Windows 10?

### ISSUE THREAD

**Issue by crimsoncandy** [FlyGoat/RyzenAdj#51]
On my previous Windows 10 installation I managed to get `ryzenadj` work without administrator privileges (You have to take my word for it, as I reinstalled Windows and I forgot to backup ryzenadj folder that I was using before). I used some combination of `ryzenadj` included in ryzencontroller and (from here) ryzenadj-win64-release.zip
Also secure boot is disabled on my laptop, and the processor is ryzen 5 2500u.

On my current Windows install when I run without admin privileges, I get following error.
```
WinRing0 Err: 0x2Unable to get PCI Obj
Unable to init ryzenadj, check permission
```

I am really not sure how I managed to get it working before and not now, maybe a bug in Windows or my bios?
PS: This is more of a question rather than issue.

**Comment by FlyGoat** [comment]
You can never run ryzenadj without administration permission.
