### ISSUE TITLE
Ryzen 4000 series compatibility

### ISSUE THREAD

**Issue by Freekers** [FlyGoat/RyzenAdj#52]
Is RyzenAdj already compatible with the new Ryzen 4000 series?

Thank you!

**Comment by FlyGoat** [comment]
It is known that TDP function works with Renoir.

**Comment by adam900710** [comment]
Doesn't look like the case, at least for Ryzen Pro 4750U

I set the TDP to 25W/35W, but during kernel building (make -j20), no difference in CPU temp (~60C), nor the completion time
(<6min for the localmodconfig), nor the CPU freq (around 2.1~2.2Ghz for all cores).

While for another laptop, using 4800U, its TDP is much higher (25W I guess?), it finishes kernel compile faster and all cores runs around 3Ghz for all core loads.

Did I miss something or the default setup of Ryzen Pro 4750U is already 25W/35W, not the 15W claimed?

**Comment by adam900710** [comment]
Another try, now 30/45W.

No difference in CPU freq, temp, nor kernel compile time.

Does this mean Ryzen Pro lineup has a different config? Or the upper limit is harded coded in certain lineup?

What info can I provide to debug?

**Comment by FlyGoat** [comment]
@adam900710 I just got a 4800U laptop (Yoga 14s) and will do some test in next few days.

Thanks.

**Comment by adam900710** [comment]
That's great.

It would be even better if the current and power monitoring can be integrated into k10temp module (just like the desktop ryzen 3000).

**Comment by bezirg** [comment]
> That's great.
> 
> It would be even better if the current and power monitoring can be integrated into k10temp module (just like the desktop ryzen 3000).

I think k10temp renoir support is supposed to come with kernel 5.8. not 100% sure though

**Comment by adam900710** [comment]
> > That's great.
> > It would be even better if the current and power monitoring can be integrated into k10temp module (just like the desktop ryzen 3000).
> 
> I think k10temp renoir support is supposed to come with kernel 5.8. not 100% sure though

It's just temp monitoring (Tctl and Tdie) in 5.8. In comparison, the desktop ryzen 3000 has Vcore, Vsoc, Tctl, Tdie,Tccd1, Tccd2 (for two ccd chips), Icore and Isoc (which can be used to calculate the Pcore and Psoc)

**Comment by FlyGoat** [comment]
> 
> 
> > > That's great.
> > > It would be even better if the current and power monitoring can be integrated into k10temp module (just like the desktop ryzen 3000).
> > 
> > 
> > I think k10temp renoir support is supposed to come with kernel 5.8. not 100% sure though
> 
> It's just temp monitoring (Tctl and Tdie) in 5.8. In comparison, the desktop ryzen 3000 has Vcore, Vsoc, Tctl, Tdie,Tccd1, Tccd2 (for two ccd chips), Icore and Isoc (which can be used to calculate the Pcore and Psoc)

That will need extra effort on reverse engineering SMN sensor registers and currently out of my scope.

**Comment by moson-mo** [comment]
> Ryzen Pro 4750U

Hmm. Working fine here on a T14s with that CPU (at least on AC).

Which NB do you have? Maybe there are some limits applied by the EC as well. (I had that issue with my previous T480s where I had to trick the EC too; with an Intel CPU though)

**Comment by siu00adg** [comment]
Same, T14s 4750U working great for me. Weirdly Geekbench only scores well (74xx multi) on AC and on battery it falls to 5xxx. When I run my own code (e.g. a numpy neural network) it runs like a beast on battery and AC.

**Comment by adam900710** [comment]
It's now working after commit d5e03022844edfb44dc70ad493313b5b5d1f39fc.
