### ISSUE TITLE
Ryzenadj --info

### ISSUE THREAD

**Issue by dcarusil** [FlyGoat/RyzenAdj#57]
Hello,

I was only wondering about the -i argument. I see no output and was curious if it is implemented? My understanding is it will gather current settings from the device, is it possible to gather OEM default settings? Or is it impossible to read the registers/memory?

Steps;
Restart pc
Open admin cmd
ryzenadj --info

Thank you.

**Comment by dcarusil** [comment]
I realize amd uprof can capture default stapm and such. I am just curious :)

**Comment by Falcosc** [comment]
You can not read the default values. You can only read active values. Tools like uprof does store the active value as default value during initialization.

Since RyzenAdj does not keep running, we would lose the last extracted active value after each call of RyzenAdj.
