### ISSUE TITLE
Stop closing after applying settings

### ISSUE THREAD

**Issue by storm1er** [FlyGoat/RyzenAdj#6]
Hi guys,

It would be nice if the adj window could have standard features:
- Minimize button
- Close Button
- Apply without closing (or add a tick "Closing on applying settings")

**Comment by FlyGoat** [comment]
Thanks for your suggestions.
Just forwarded them to the GUI develper.

**Comment by storm1er** [comment]
Actually working on a advanced electron app if you're interested. 
Will be open source btw.

**Comment by storm1er** [comment]
@FlyGoat 
I would like to implement your compiled ryzenadj.exe into my project.
Obviously, this repo will keep the development and source code, my project will only contain the compiled ryzenadj.exe and the needed dlls.

See https://gitlab.com/le.storm1er/ryzen-controller.

**Comment by FlyGoat** [comment]
Thanks for your works.
Will promote "ryzen-controller" in readme.
