### ISSUE TITLE
Wrong temperature unit

### ISSUE THREAD

**Issue by crimsoncandy** [FlyGoat/RyzenAdj#61]
In new ryzenadj v0.6.2, I guess temperature unit is changed from Celsius to some other unit (It is not Kelvin either)
After applying my usual `--tctl-temp=95` (which used to work fine with older versions)
CPU locks to 400MHz (Task Manager)
GPU locks to 200MHz (AMD OSD)
Memory locks to 400MHz (AMD OSD)
My guess is 95 in some other unit is pretty low so it start power throttling.

And applying some high value like 9500 for temperature fixes the issue.

OS: Windows 10 pro 1909
CPU: Ryzen 5 2500u

**Comment by FlyGoat** [comment]
Is it a regression of v0.6.2, or did it happen on previous versions?

**Comment by sbski** [comment]
No that was not intentional

**Comment by FlyGoat** [comment]
> No that was not intentional

Oops, to confirm, serivce id on Raven is `0x1f` and on Picasso is `0x1a`?

I'll release a emergency hotfix for this.

**Comment by sbski** [comment]
I got it fixed! No, Raven and Pocasso should both be 0x1F. I think I just made a typo when I was adding support for Renoir. I got a new build and updated the code already. @crimsoncandy 0.6.3 has the fix for it. Let me know if it works

**Comment by crimsoncandy** [comment]
@sbski I tested version 0.6.3, it is working now.

**Comment by sbski** [comment]
> @sbski I tested version 0.6.3, it is working now.
Great!  I am looking into adding in some more features here sometime.
