### ISSUE TITLE
Unable to apply ryzenadj

### ISSUE THREAD

**Issue by Bsiate** [FlyGoat/RyzenAdj#64]
Hi,

First of all, thank you for creating that program.
Until 2 weeks I've been using Ryzenadj totally fine, but after playing Lol I just checked my temperature of the cpu just out of curiosity and it went up to 100° which shocked me, and i tried to stop ryzenadj, but my laptop just immediately crashed, although I maxed my temperature to 85°. After that happened I just let my laptop sit there for a while to cool down. Starting my laptop, everything works fine, but ryzenadj just wouldn't apply anymore. Sometimes it says it has been fully executed but after 30 seconds or so, it displays me that it's Unable to apply ryzenadj.
I'd be very thankful if someone could help me solve this problem.

Sincerely,
Erik

**Comment by FlyGoat** [comment]
It sounds like a ryzen-controller issue if you're using that. Unable to apply ryzenadj is not likely to be a RyzenADJ error message.
