### ISSUE TITLE
Unable to apply ryzenadj error w/ Ryzen Controller

### ISSUE THREAD

**Issue by DeiraMarceline** [FlyGoat/RyzenAdj#65]
I'm sure this issue has been reported various times before, but I've been unable to find a fix. I use Ubuntu 20.04.1 with an AMD Ryzen 2700U with Vega 10 graphics.

The RyzenAdj binary is in the default location and the settings I am attempting to apply are:
--tctl-temp = 85
--stapm-limit = 30000
--fast-limit = 35000
--slow-limit = 20000

Additionally, some warning messages come up in Terminal when I open up Ryzen Controller.
To run Ryzen Controller, I use the following code in the terminal:

`$ sudo ryzen-controller --no-sandbox'

``(ryzen-controller:10534): libappindicator-WARNING **: 23:50:49.472: Unable to get the session bus: Unknown or unsupported transport “disabled” for address “disabled:”`
`(ryzen-controller:10534): LIBDBUSMENU-GLIB-WARNING **: 23:50:49.472: Unable to get session bus: Unknown or unsupported transport “disabled” for address “disabled:”`
`(ryzen-controller:10534): libnotify-WARNING **: 23:50:51.161: Failed to connect to proxy`

Hopefully I've provided enough information for someone to tell me what's been going wrong here.

**Comment by FlyGoat** [comment]
Please kindly forward this issue to the downstream project ryzen-controller.
https://gitlab.com/ryzen-controller-team/ryzen-controller/-/issues

It is out of the scope of RyzenAdj.

Thanks.
