### ISSUE TITLE
"Unknown Ryzen processor, won't work" message with brand new 3600X

### ISSUE THREAD

**Issue by SimoFiuz** [FlyGoat/RyzenAdj#66]
Hello all. 

Manjaro Linux, kernel 5.8.0. I just swapped the motherboard, cpu and ram of this system, was previously on an i7 4790K. 

Current CPU is a Ryzen 5 3600X, mobo is an ASRock AM4/X570M Pro4
The OS was working out of the box, I just installed amd-ucode as suggested in the Arch wiki page.

Problem is that ryzenadj returns the error 

"Unknown Ryzen processor, won't work
Unable to init ryzenadj, check permission"

whether I run it as root or as a regular user.

Are there any more steps I should take to let it recognize my CPU?

Thanks.

**Comment by Thesola10** [comment]
@SimoFiuz You just closed the issue, is that voluntary? And if so, can you clarify the solution you found? (if any)

**Comment by FlyGoat** [comment]
@Thesola10 RyzenADJ is not designed to work on non-APU systems. So 3600X is not our supported platform. Previous versions won't check system type but we added this limitation to our recent release.

**Comment by SimoFiuz** [comment]
I don't know C very well but I took a peek into the code and noticed that it's a moot issue because my platform isn't supported.

Sorry for wasting your time.
