### ISSUE TITLE
Failed to setmin_socclk_freq on Ryzen 4900HS

### ISSUE THREAD

**Issue by hyphone** [FlyGoat/RyzenAdj#67]
Hello and good day,

I tried to set the min frequency on a Ryzen 4900HS without success.

`Failed to setmin_socclk_freq on Ryzen 4900HS`

This is the output.

Default it's clocked above 1300 MHz and sadly does not go below this.

**Comment by sbski** [comment]
So Renoir does not have the commands to support it. I will be adding some debug print here. I am also adding a bunch of Skin Temperature Tracking commands here that will make things fun.

**Comment by sbski** [comment]
I implemented a command not supported feature into the sst_commands branch. I tested it and it appears to be working perfectly 😃
