### ISSUE TITLE
Unable to init ryzenadj even have admin permission

### ISSUE THREAD

**Issue by AlaricGilbert** [FlyGoat/RyzenAdj#73]
![image](https://user-images.githubusercontent.com/36405110/98994703-2e183980-256b-11eb-817d-d33ca9910c6f.png)
Cannot run example instruction even if I have admin permission
OS:  Windows10 2004
CPU: 4800h
Core Isolation's Memory Integrity mentioned by other issues never opened.
![image](https://user-images.githubusercontent.com/36405110/98995028-b7c80700-256b-11eb-8e4a-b542faa95447.png)

**Comment by AlaricGilbert** [comment]
build from latest commit also not working...
it generates a debug error: heap corruption
![image](https://user-images.githubusercontent.com/36405110/98996055-3cffeb80-256d-11eb-855e-b9d167cfd6c1.png)

**Comment by FlyGoat** [comment]
Maybe you have to disable secure boot and other security features.

The heap corruption is really wired. Actually I don't think RyzenADJ has anything to do with that. I'd recognise it as a WinRing0 issue. Any further debug information?

**Comment by FlyGoat** [comment]
Closing, I'll reopen if there are further feedback.
