### ISSUE TITLE
Question: disable DRAM powersaving feature

### ISSUE THREAD

**Issue by Benman2785** [FlyGoat/RyzenAdj#78]
hi,

my AN515-42 (Acer Nitro 5) with Ryzen 2500U + RX560X got a "problem" with BIOS 1.16

they enabled dynamic RAM as powersaving feature - now my 16GB DDR4-2400CL16 clocks from 400MHz up to 1200MHz - and in some games it doesnt boost up to max speed (1200MHz CL16) (like in Cyberpunk2077 it is at 933MHz when playing - only when loading a savegame it reaches 1200MHz)

is there a way to force it to 2400MHz? or to disable that powersaving feature?

**Comment by FlyGoat** [comment]
You can try to tweak FCLK related options.

**Comment by Benman2785** [comment]
in what way?
make it dynamic aswell? like min 400MHz and max 1200MHz? does that work synced with ramspeed?

of force 1200 on min and max - will try that tomorrow ;)

**Comment by Benman2785** [comment]
ok, can be closed

min/max at 1200MHz fixes RAM speed to 1200MHz - thank you ;)

**Comment by Falcosc** [comment]
Looks like your platform support adjusting fabric clock. @Benman2785 please could you help me finding which metric is used to report the max speed, and which is used for the min speed?
Here is the description: https://github.com/FlyGoat/RyzenAdj/issues/94

Thank you
