### ISSUE TITLE
Add CPU Skin Temperature Limit for Renoir

### ISSUE THREAD

**Issue by Falcosc** [FlyGoat/RyzenAdj#82]
Hello, 

I would like to set CPU Skin Temperature Limit.

### Why do we need it?
PPT LIMIT APU (STAPM Limit Offset 24) gets applied if SST VALUE APU (STAPM Limit Offset 92) does exceed SST LIMIT APU (STAPM Limit Offset 88, 0x38 on Renoir)
Skin temperature name in HWiNFO is "CPU Skin Temperature" and gets set to 45° on my notebook. I need 50°C for long workloads to prevent 15W PPT LIMIT APU

### What can be done?

To fix this we need to change SST LIMIT APU. For higher accepted temperatures we could use higher PPT LIMIT APU, but I did find a way to change this Power limit, which is not important at all, it would be enough to add SST LIMIT APU.

To Change Skin Temperature Limit, on Renoir ec address 0x38 will accept an UInt. But the value in °C need to be multiplied by 256 if you write in the same 0x38 address. Looks like write address is maybe 8 bits off 0x38.

### Should I create a pull request?

I didn't prepare a Developer Environment for this project, so I could create a branch without building it. Would you like to have an untested branch?

Kind Regards
Falco

**Comment by FlyGoat** [comment]
Github actions will automatically build and create binary for test.
Please create a PR to trigger Github action.

Thanks.

**Comment by Falcosc** [comment]
> 
> 
> Github actions will automatically build and create binary for test.
> Please create a PR to trigger Github action.
> 
> Thanks.

A binary for each open PR? That's great, glad that I did mention it instead of starting setting up an environment.

I will keep the 256 multiplication, because I don't know anything about writing into IO registers :)

**Comment by Falcosc** [comment]
Values in the lower 8 bits does actually get applied as fraction. Didn't expect this to happen. Is there a datatype which does store the lower 8 bits as a fraction? It could be that this value is actually just divided by 256.
