### ISSUE TITLE
Does not work in acer aspire 3 a315-42g-r6fz

### ISSUE THREAD

**Issue by Haozinho** [FlyGoat/RyzenAdj#89]
Specs:
CPU: Ryzen 5 3500u
RAM: 8gb ddr4 2666mhz
GPU: 540x

When it opens it does not confirm the TDP and FREQUENCY, and keeps opening the program directly, not running in the background.

**Comment by Falcosc** [comment]
@Haozinho did you create the issue in the wrong repository? We don't have anything which can distinguish between run in the background.

Have a look here: https://github.com/FlyGoat/RyzenAdj
You can try downloading RyzenAdj and see if acer does allow you to do some things :)
